# Setup
title: Enjoy Your Haggis
tagline: 
url: https://www.dannysleaving.us
paginate: 1
baseurl: ""
permalink: pretty
repository: P-Brower/goodbye

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options


# Specify the author for blog posts
author:
  name: The Peanut Gallery 🥜
description: "So Long, and Thanks for All the Fish"
banner: https://dannysleaving.us/assets/enjoy.jpg

# Custom vars
version: 3.0.0
