# Setup
title: Dear Traitor
tagline:
url: https://dannysleaving.us
paginate: 1
baseurl: ""
permalink: pretty
repository: P-Brower/goodbye

# Gems


# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options


# Specify the author for blog posts
author:
  name: The Peanut Gallery

# Custom vars
version: 3.0.0
